/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedLessonScenarioIdRouteImport } from './routes/_authenticated/lesson.$scenarioId'
import { Route as AuthenticatedDrillNumbersRouteImport } from './routes/_authenticated/drill.numbers'
import { Route as AuthenticatedCategoryCategoryIdRouteImport } from './routes/_authenticated/category.$categoryId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLessonScenarioIdRoute =
  AuthenticatedLessonScenarioIdRouteImport.update({
    id: '/lesson/$scenarioId',
    path: '/lesson/$scenarioId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDrillNumbersRoute =
  AuthenticatedDrillNumbersRouteImport.update({
    id: '/drill/numbers',
    path: '/drill/numbers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoryCategoryIdRoute =
  AuthenticatedCategoryCategoryIdRouteImport.update({
    id: '/category/$categoryId',
    path: '/category/$categoryId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/category/$categoryId': typeof AuthenticatedCategoryCategoryIdRoute
  '/drill/numbers': typeof AuthenticatedDrillNumbersRoute
  '/lesson/$scenarioId': typeof AuthenticatedLessonScenarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/category/$categoryId': typeof AuthenticatedCategoryCategoryIdRoute
  '/drill/numbers': typeof AuthenticatedDrillNumbersRoute
  '/lesson/$scenarioId': typeof AuthenticatedLessonScenarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/category/$categoryId': typeof AuthenticatedCategoryCategoryIdRoute
  '/_authenticated/drill/numbers': typeof AuthenticatedDrillNumbersRoute
  '/_authenticated/lesson/$scenarioId': typeof AuthenticatedLessonScenarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/progress'
    | '/category/$categoryId'
    | '/drill/numbers'
    | '/lesson/$scenarioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/progress'
    | '/category/$categoryId'
    | '/drill/numbers'
    | '/lesson/$scenarioId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/progress'
    | '/_authenticated/category/$categoryId'
    | '/_authenticated/drill/numbers'
    | '/_authenticated/lesson/$scenarioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lesson/$scenarioId': {
      id: '/_authenticated/lesson/$scenarioId'
      path: '/lesson/$scenarioId'
      fullPath: '/lesson/$scenarioId'
      preLoaderRoute: typeof AuthenticatedLessonScenarioIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drill/numbers': {
      id: '/_authenticated/drill/numbers'
      path: '/drill/numbers'
      fullPath: '/drill/numbers'
      preLoaderRoute: typeof AuthenticatedDrillNumbersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/category/$categoryId': {
      id: '/_authenticated/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof AuthenticatedCategoryCategoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedCategoryCategoryIdRoute: typeof AuthenticatedCategoryCategoryIdRoute
  AuthenticatedDrillNumbersRoute: typeof AuthenticatedDrillNumbersRoute
  AuthenticatedLessonScenarioIdRoute: typeof AuthenticatedLessonScenarioIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedCategoryCategoryIdRoute: AuthenticatedCategoryCategoryIdRoute,
  AuthenticatedDrillNumbersRoute: AuthenticatedDrillNumbersRoute,
  AuthenticatedLessonScenarioIdRoute: AuthenticatedLessonScenarioIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
